### ISSUE TITLE
Criar Tela - Home Page

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#11]
Desenhar a tela inicial.

**Comment by TiagoAraujo12** [comment]
Opção para homePage.



![Image](https://user-images.githubusercontent.com/125419720/230676338-35348f5c-9987-45a0-8755-e7aba88601e1.png)
![Image](https://user-images.githubusercontent.com/125419720/230676336-2f674654-f0da-42c7-abc6-982fcd8638b9.png)




[Home Page.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager/files/11181376/Home.Page.pdf)

**Comment by g413rie1** [comment]
![image](https://user-images.githubusercontent.com/127675409/232643499-e89b2684-cb9b-448b-a24c-0f9ef18d8623.png)

**Comment by Maia2098** [comment]
@TiagoAraujo12 , gentileza criar uma tela da aplicação com foco na pesquisa de filmes. 
Referência: imagem que o @g413rie1 acabou de colar acima.

Obrigado!!

**Comment by TiagoAraujo12** [comment]
@Maia2098 @g413rie1 

Fiz um esboço para que vocês possam avaliar e criticar. 

[Pesquisa.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager/files/11267218/Pesquisa.pdf)

[Pesquisa - Click.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager/files/11267219/Pesquisa.-.Click.pdf)

**Comment by Maia2098** [comment]
@g413rie1 , gentileza validar. Acho que ficou excelente!!
