### ISSUE TITLE
Criar Tela - Login

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#12]
Elaborar tela de login do usuário.

**Comment by TiagoAraujo12** [comment]
Opção de página de Login + Cadastro



![Image](https://user-images.githubusercontent.com/125419720/230738731-e894b923-f215-4c13-a961-be58d7949edd.png)
[Login1.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager/files/11183956/Login1.pdf)




Opção de página de Login e Cadastro Separadas.



![Image](https://user-images.githubusercontent.com/125419720/230672083-b71b0b0f-1576-43e7-a972-56c65405ed02.png)
