### ISSUE TITLE
Criar Tela - Página da Lista de Filmes

### ISSUE THREAD

**Issue by g413rie1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#14]
página da lista de filmes

**Comment by RaimundoSMN** [comment]
Coloquei o espaço para pesquisa na tela de listas.

Deixei sem o nome do aplicativo pois pesquisei na internet e achei um aplicativo com este nome.

https://www.figma.com/file/ZOzeh9XfVaClgnKft4k7NO/Listas?node-id=0%3A1&t=PtETGqoyRPn8ZoOI-1

**Comment by Maia2098** [comment]
@RaimundoSMN , ambas as telas ficaram ótimas! 

Apenas dois feedbacks.

Na tela dos filmes assistidos, gentileza inserir um quadro de "adicionar" igual você colocou na segunda tela.

Por fim, de baixo do nome do aplicativo, inserir um retângulo de "pesquisar" filmes.

Pode usar como base a tela de mídia que @Ana-MP elaborou.

Muito obrigado!

**Comment by Maia2098** [comment]
@RaimundoSMN , essa é a tela de referência da base de pesquisa:



![Image](https://user-images.githubusercontent.com/100796561/232823407-01d6709c-d125-41b8-a235-a201c43dee01.png)

**Comment by Maia2098** [comment]
@g413rie1 , imagem das telas do @RaimundoSMN para validação. Acho que ficaram ótimas!



![Image](https://user-images.githubusercontent.com/100796561/232930387-251e4095-2200-4991-8af6-e98ba2a5c1ae.png)
