### ISSUE TITLE
Criar Tela - Redefinição de Senha

### ISSUE THREAD

**Issue by g413rie1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#15]

**Comment by Maia2098** [comment]
@g413rie1 , elaborei no figma a redefinição da senha. Ou seja, quando o usuário já estiver dentro do sistema.

Para homologação: https://www.figma.com/file/FIqtxlJKJuBD0NzB3MmIKQ/Untitled?node-id=0%3A1&t=tVrQ12jmsdCjtdXZ-1

**Comment by Maia2098** [comment]
![Image](https://user-images.githubusercontent.com/100796561/232646830-425c6d5a-f1d8-40d5-b041-094f53f65819.png)

**Comment by Maia2098** [comment]
![Image](https://user-images.githubusercontent.com/100796561/232646924-e9795b21-4766-4cce-b05b-ee796802b3f0.png)
