### ISSUE TITLE
Criar Tela - Recuperação de Senha

### ISSUE THREAD

**Issue by g413rie1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#16]

**Comment by Maia2098** [comment]
@g413rie1 , fiz no figma a definição de recuperação da senha (tá no mesmo arquivo que a redefinição de senha). Nesse caso as telas são:


1) recuperação de senha;
2) confirmação de senha.

Eu fiz o modelo como se o sistema fosse encaminhar um link no e-mail nos usuários. Posteriormente, vamos necessitar validar se seguiremos nesse modelo.


https://www.figma.com/file/FIqtxlJKJuBD0NzB3MmIKQ/Untitled?node-id=2%3A44&t=tVrQ12jmsdCjtdXZ-1

**Comment by Maia2098** [comment]
colar as imagens aqui direto @Maia2098

**Comment by Maia2098** [comment]
![Image](https://user-images.githubusercontent.com/100796561/232647174-5eabcacb-52d6-406a-823e-4764ef25485a.png)

**Comment by Maia2098** [comment]
![Image](https://user-images.githubusercontent.com/100796561/232647245-30240e83-8e50-4d54-a6cc-b3b2003424c5.png)
