### ISSUE TITLE
Template do Site - Criar Home page

### ISSUE THREAD

**Issue by g413rie1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#19]

**Comment by Maia2098** [comment]
Nós vamos fazer o template da home page no pensamento principal que foi desenhado pelo @TiagoAraujo12 (https://github.com/orgs/ICEI-PUC-Minas-PMV-ADS/projects/357?pane=issue&itemId=25055547).

**Comment by Maia2098** [comment]
@g413rie1 , dei uma apanhada legal. Como estou usando o framework do bootstrap, tem muito pouco (quase nada) de CSS. 
Dá uma olhada.
As imagens não estão boas.
Não to conseguindo upar o vscode. Então zipei.

[index.zip](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager/files/11379142/index.zip)

**Comment by Maia2098** [comment]
Achei um vídeo legal que podemos usar para aprender o redirecionamento.

https://www.youtube.com/watch?v=qrDHQADFVHQ&ab_channel=UmestudantedeTI

**Comment by Ana-MP** [comment]
@Maia2098 Coloquei o código numa branch aqui.
