### ISSUE TITLE
Funcionalidade - Botão para redirecionamento para pág. de Listas

### ISSUE THREAD

**Issue by g413rie1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#20]

**Comment by Maia2098** [comment]
@g413rie1 , acredito que consegui resolver o direcionamento:

O bootstrap já consta com essa função quando fizemos o dropdown:



![Image](https://user-images.githubusercontent.com/100796561/236881619-7b7a6785-fb1f-4d81-9c47-0a8cb7214e4f.png)



Veja que ele já chama a possibilidade de inclusão do link, podemos utilizar esse mecanismo para as seguintes funcionalidades:

Da homepage para página das listas.
Da homepage para configurações.
Da homepage para logout.

Precisamos agora criar a página das listas e entendo que teremos cumprido todos os requisitos dessa etapa.
