### ISSUE TITLE
Template - Página de Login

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#22]
Nos moldes do desenho da página - criar a página de login.

**Comment by Maia2098** [comment]
@g413rie1 , para adiantar nossa vida, eu criei uma página simples de login que acredito que cumpre com a tela que criamos. Peço, gentileza, validar.
Está dentro do SRC.

Criei uma página específica para login.

Acho que se a gente conseguir ajustar a responsividade das imagens na home page e criar o redirecionamento do login para home e da home para página de listas, estaremos bem para etapa.

**Comment by TiagoAraujo12** [comment]
@Maia2098 @g413rie1 

Segue abaixo uma sugestão do css da tela de login que o Matheus criou. Como a nossa homepage possui uma tonalidade mais clara, fiz essa proposta para ficar mais proximo.

![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager/assets/125419720/fa548fbe-91f2-4021-843f-7bb4ebbebfff)

imagem da logo: 
![image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager/assets/125419720/dec3637d-85e8-4eb4-9e97-7fbe90525b50)


`body{
    background-color: #1B1F27;
    font-family: 'poppins',sans-serif;
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}

.area-login{
    background-color: rgb(255, 255, 255);
    display: flex;
    height: 100vh;
    justify-content: center;
    align-items: center;
}

.Login{
    display: flex;
    flex-direction: column;
    align-items: center;
    border-radius: 16px;
    background-color: #fbfbff;
    width: 355px;
    height: 320px;   
    padding: 35px;
}

.login form{
    display: flex;
    width: 100%;
    flex-direction: column;
}

.login input{
    margin-top: 10px;
    background-color: #bcbcbd;
    padding-left: 12px;
    color: #fcfdfe;
    border: none;
    height: 45px;
    outline: none;
    border-radius: 14px;

}

.login img{
    width: 349px;
    height: auto;
}

input::placeholder{
    color: #fcfdfe;
    font-size: 20px;
}

form [type="submit"] {
    display: block;
    background-color: #5568fe;
    font-size: 20px;
    text-transform: uppercase;
    font-weight: bold;
    cursor: pointer;
}

p{
    color: #5568fe;
}

a{
    color: #5568fe;
    text-decoration: none;
    margin-left: 10px;
}`

**Comment by Maia2098** [comment]
@g413rie1 , aderi a sugestão do Tiago e mudei o CSS do login na SRC.

**Comment by Maia2098** [comment]
@g413rie1 apaguei a pasta "login" dentro da src para seguir as recomendações do Professor. Criei um novo formato de login que foi o que eu consegui fazer e testar a criação de usuários.
