### ISSUE TITLE
@RaimundoSMN , mensagem para te lembrar de elaborar o texto da sprint.

### ISSUE THREAD

**Issue by RaimundoSMN** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#24]
@Maia2098 
Prezado Matheus, 
Tive um problema pessoal que me obrigou a me afastar. Tentei manter contato com o trabalho lendo algumas coisas durante umas oportunidades mas não tive tempo pra escrever. 
Pretendo reiniciar as atividades hoje.
Espero dar um início e terminar amanhã. 

@RaimundoSMN , mensagem para te lembrar de elaborar o texto da sprint.
Obrigado!

_Originalmente postado por @Maia2098 em https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager/issues/21#issuecomment-1538728713_

**Comment by Maia2098** [comment]
Comentário postado fora do issue original. Issue fechado.
