### ISSUE TITLE
Registro de Testes do Software

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#30]
Realizar o registro mediante gravação de tela (vídeo) dos testes do software.

**Comment by RaimundoSMN** [comment]
> Realizar o registro mediante gravação de tela (vídeo) dos testes do software.

Pode ser print?

**Comment by g413rie1** [comment]
@RaimundoSMN Sim
