### ISSUE TITLE
Equipe de Trabalho

### ISSUE THREAD

**Issue by g413rie1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#6]
Definir o papel de cada membro do grupo. Divisão entre Product Owner, Scrum Master e equipe de desenvolvimento.

**Comment by Maia2098** [comment]
A organização da equipe está dessa forma:

Scrum Master: Matheus Maia.

Product Owner: Gabriel Santana Lourenço.

Equipe de Desenvolvimento: Ana Maria Pessoa, Raimundo Sales de Melo Neto e Tiago Carvalho Taveira Araujo.


Essa disposição foi incluída e já está nos docs.
