### ISSUE TITLE
Projeto de Interface - Criar Fluxo de Usuário

### ISSUE THREAD

**Issue by g413rie1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#7]
Criar fluxo de usuário.

**Comment by g413rie1** [comment]
![Image](https://user-images.githubusercontent.com/127675409/231313879-ee75b526-2323-4c60-8a77-4b3e0ebb94e3.png)

Fluxograma para login

**Comment by Maia2098** [comment]
@g413rie1 , fiz a inclusão de um outro fluxo que foi baseado na homepage. Gentileza verificar:

https://www.canva.com/design/DAFgUFO_sTw/fML82uDKQyyQCvhMCLQVZg/edit?utm_content=DAFgUFO_sTw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Maia2098** [comment]
@g413rie1 , consegui fazer o fluxograma da senha. Veja se está de acordo:


Caso queira editar direto no Canva: https://www.canva.com/design/DAFge6pt2Mw/hmI5CekO_rrNeawWsk6BTQ/edit?utm_content=DAFge6pt2Mw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton


![Image](https://user-images.githubusercontent.com/100796561/232894806-24ab6bfe-4bb3-4aaf-bb8a-bc7b6ca1db29.png)

**Comment by Maia2098** [comment]
Faltam dois fluxogramas., @Maia2098

**Comment by Maia2098** [comment]
@g413rie1 , fluxograma de pesquisar filme:

Caso queira no Canva: https://www.canva.com/design/DAFggEKtOZ4/5r_2_bmx6qAdUXrOx9KDDQ/edit?utm_content=DAFggEKtOZ4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

![Image](https://user-images.githubusercontent.com/100796561/232935195-7cbb7c43-296c-4be3-9681-a42d4003d0aa.png)

**Comment by Maia2098** [comment]
@g413rie1 , agora o fluxograma da visualização da lista:

https://www.canva.com/design/DAFggCZqKec/mvKdhf2RVTzJCU4m4k9lug/edit?utm_content=DAFggCZqKec&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton



![Image](https://user-images.githubusercontent.com/100796561/232937372-f66eef7a-42b3-4079-96c0-d1c1f1388e63.png)

**Comment by g413rie1** [comment]
![Sim](https://user-images.githubusercontent.com/127675409/232945930-a872b9ce-70d7-428e-bc65-c9c6a153be25.png)

**Comment by g413rie1** [comment]
[Fluxo de usuário do Sales](https://www.figma.com/file/wh2ecDtJEa9a37lLoq5eA3/Untitled?node-id=0-1[](url))
