### ISSUE TITLE
Projeto de Interface - Validar Fluxo de Usuário

### ISSUE THREAD

**Issue by Maia2098** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-movie-manager#9]

**Comment by RaimundoSMN** [comment]
Criei um fluxo de usuário com base em TELAS.
Deu um total de 10 telas.
Vejam e opinem.
https://www.figma.com/file/wh2ecDtJEa9a37lLoq5eA3/Untitled?node-id=0%3A1&t=rtMsQg22h1zIJOpo-1

**Comment by RaimundoSMN** [comment]
![Image](https://user-images.githubusercontent.com/126730478/233166165-b5d66e1d-e12f-4ee9-9d02-4c4ba020a9fb.jpg)
